export const AUTH_EVENT = 'AUTH_EVENT';
export const SETTINGS_EVENT = 'SETTINGS_EVENT';
export const ADD_TO_LIBRARY = 'ADD_TO_LIBRARY';
export const REMOVE_FROM_LIBRARY = 'REMOVE_FROM_LIBRARY';
export const ADD_TO_BOOKMARKS = 'ADD_TO_BOOKMARKS';
export const REMOVE_FROM_BOOKMARKS = 'REMOVE_FROM_BOOKMARKS';